# Generated by Django 4.0.3 on 2022-04-19 04:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_Creacio_Tablas_Platos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platos',
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('foto', cloudinary.models.CloudinaryField(max_length=255)),
                ('disponible', models.BooleanField(default=True)),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'platos',
            },
        ),
        
    ]
